#pragma once

#define CAM_WIDTH                   320
#define CAM_HEIGHT                  240
#define CAM_FRAME_BYTES             (CAM_WIDTH * CAM_HEIGHT)

// XCLK is generated by the ESP through LEDC and fed to the sensor. On the S3 it
// is divided from 80 MHz, so use a divisor: 20, 16, 10, or 8 MHz. Lower this
// first if the capture layer logs FB-OVF (frames arriving faster than the copy
// to PSRAM can keep up).
#define CAM_XCLK_FREQ_HZ            20000000

// Frame buffers in the esp32-camera pool. Keep at 2 or more so capture and the
// stream consumer can overlap without stalling.
#define CAM_FB_COUNT                2

#define CAM_JPEG_QUALITY            80

#define CAM_START_WITH_TEST_PATTERN 1